spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/hollywood?createDatabaseIfNotExist=true
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: ERROR
    org.hibernate: ERROR

jwt:
  secret: JWTSuperSecretKey
  expirationInMs: 604800000
