spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hollywood
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: admin
      password: admin
jwt:
  secret: JWTSuperSecretKey
  expirationInMs: 604800000
